### ISSUE TITLE
Optimize variant filtering/prioritization

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/VAPr#15]
Write unit tests for queries, optimize performance

**Comment by kmfisch** [comment]
also double check query syntax (False vs false, etc)

**Comment by AmandaBirmingham** [comment]
tests/test_filtering.py contains unit tests for queries.  Query performance has been improved by including sample id constraints only when we want to query a subset of sample ids rather than all of them (see https://github.com/ucsd-ccbb/VAPr/blob/8a232f170e2d087fb5c31b9b95c95e43b2e9ade3/VAPr/filtering.py#L98 )
